# Generated by Django 2.2.1 on 2019-06-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iris',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('petal_length', models.FloatField()),
                ('petal_width', models.FloatField()),
                ('sepal_length', models.FloatField()),
                ('sepal_width', models.FloatField()),
                ('classification', models.TextField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Irises',
            },
        ),
    ]
