# Generated by Django 2.2.1 on 2019-06-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iris',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
