# Generated by Django 2.2.1 on 2019-06-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0002_auto_20190611_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='iris',
            name='iris_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
