# Generated by Django 2.2.1 on 2019-06-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0003_iris_iris_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iris',
            name='iris_id',
        ),
        migrations.AlterField(
            model_name='iris',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
